server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://39.96.172.135:27017
      database: xc_cms
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    host: 39.96.172.135
    port: 5672
xuecheng:
   mq:
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1